application:
  title: "Benchmarker API for Benchmarker WebApp"
  version: "v1.0"
logging:
  level:
    root: INFO
    web: INFO

server:
  port: 8090
  error:
    include-message: always
    include-binding-errors: always
    whitelabel:
      enabled: true
spring:
  application:
    name: bm-data-api
  mvc:
    pathmatch:
          matching-strategy: ANT_PATH_MATCHER
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:file:./bmapi.db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    

jwt:
  expiration: 15 #in minutes
  secret: "cfgsecret"
  issuer: "cfgsolucoes.com"
  
rememberme:
  expiration: 1296000 # 15 days
  secret: "cfgsecret"
  key: "remember-me"

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include : '*'