SELECT 1 from DUAL;
--INSERT INTO "USER"("ID","ACCOUNT_NON_EXPIRED","ACCOUNT_NON_LOCKED","LAST_ALTERATION_USER","LAST_ALTERATION_DATE","CREDENTIALS_NON_EXPIRED","ENABLED","PASSWORD","USERNAME","UUID")
--VALUES(NEXT VALUE FOR SEQUENCE_GENERATOR_TO_USER_ID,TRUE,TRUE,NULL,CURRENT_TIMESTAMP,TRUE,TRUE,'$2a$10$/tYFXzmN.OCiuQL14CuJPurrFp6.ZpzP7TxLYeSObMIkzKZCPAq4G','test@test.com',RAWTOHEX('test'));
